### ISSUE TITLE
Move from github pages/octopub to data.okfn.org

### ISSUE THREAD

**Issue by andylolz** [datasets/dac-crs-codes#37]
It looks nicer & more official.

Could even see if they’re interested in making it a core package? (/cc @rufuspollock?)

### UPDATE: Steps to moving this to frictionless data core dataset:

 - [x] Update repo structure to match required format (e.g. move data from `gh-pages` branch to `/data` directory)
 - [x] Standardise output CSV naming (bit muddled at the moment)
 - [x] Make scraper remove temporary CSVs (generated along the way, that the final CSVs are generated from)
 - [x] Remove anything to do with fetching the (out-of-date) XML. This is just about the XLS file that contains the canonical lists
 - [x] Clean up datapackage.json (e.g. add dataset descriptions; schema definitions; license; pretty print etc)
 - [x] Make @zelima an owner
  - [x] Consider moving bot code (auto-generate PRs when data changes) to a separate repo. Check how other core scrapers do this
 - [x] @zelima moves repo to @datasets org
- [x] Send a PR to [datasets/registry](https://github.com/datasets/registry/blob/master/core-list.txt) to include [datasets/dac-crs-codes](https://github.com/datasets/dac-crs-codes)

**Comment by rufuspollock** [comment]
@andylolz that would be great! We need to move it to http://github.com/datasets - that's how the process works.

If you want to do that can you add @zelima as an admin on this project and then he can move it across (with you remaining as an admin and them managing curator)

**Comment by andylolz** [comment]
> that would be great!

Brilliant!

> If you want to do that can you add @zelima as an admin on this project and then he can move it across (with you remaining as an admin and them managing curator)

I _don’t think_ I can add admins to a personal repo… Only an org repo. But I can just request a transfer to @datasets and then someone can approve && make a team where I’m an admin for that one repo?

Looks like I also need to restructure a bit (I currently have data in a branch, but that’s not crucial.) Anything else I need to do to make it appear on http://data.okfn.org/data/core/dac-crs-codes ? Thanks!

**Comment by andylolz** [comment]
EDIT My mistake – I can’t request a transfer after all! So your strategy is correct, @rufuspollock! I’ve moved the repo to an org account and sent an invite to @zelima.

**Comment by andylolz** [comment]
Okay I’ve added a list of tasks (mostly for me) to this issue description.

**Comment by zelima** [comment]
@andylolz Hi, I see you checked the task about adding me as an owner. I got the invitation but actually am not able to accept getting 
`Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account` while I am.

So please resend

**Comment by andylolz** [comment]
> I got the invitation but actually am not able to accept

Yeah, sorry, I did it wrong initially! (invited you as collaborator to personal repo; then revoked).

But looks like you’re in now! I’ve just made you an owner:
![screen shot 2017-06-30 at 15 58 10](https://user-images.githubusercontent.com/464193/27741482-2d991f8a-5dad-11e7-9607-d25d423266b4.png)

**Comment by zelima** [comment]
@andylolz confirm. So I'm waiting for you to finalize it

**Comment by andylolz** [comment]
Okay – finalised!

@zelima: Could you transfer to @datasets, and give me admin permissions over the repo so I can maintain it? Thanks!

**Comment by andylolz** [comment]
@zelima: Bumping because I am impatient / excited 😃  🚀  🙌  :robot:

**Comment by zelima** [comment]
@andylolz apologise somehow missed the previous comment.
FIXED  https://github.com/datasets/dac-crs-codes

**Comment by andylolz** [comment]
Awesome! Thanks @zelima

**Comment by andylolz** [comment]
@rufuspollock @zelima thanks again! I’ve written a draft blog about it here: https://gist.github.com/andylolz/1cb6242ae243bd56647cc5aea1623775

Let me know if you have any changes. We’ll put it on the [Publish What You Fund](http://www.publishwhatyoufund.org/) blog next week.

**Comment by rufuspollock** [comment]
@andylolz that's great - maybe we also cross post on open knowledge labs (?). /cc @danfowler because of link with data packages and frictionless data.

**Comment by andylolz** [comment]
That would be great! It’s going on the PWYF on Monday, apparently.

**Comment by danfowler** [comment]
Great, will publish after it's out.

**Comment by danfowler** [comment]
Thanks @andylolz for writing, and thanks @rufuspollock for the cross post suggestion 👌 

http://okfnlabs.org/blog/2017/07/10/dac-and-crs-code-lists-frictionless-data.html
